### ISSUE TITLE
您好咨询一下使用时候出现的一个bug

### ISSUE THREAD

**Issue by yw2278** [inisis/brocolli#10]
![image](https://user-images.githubusercontent.com/22030956/63824877-36e31680-c98b-11e9-831b-627d2dbe1879.png)
这个您这知道怎么解决么

**Comment by inisis** [comment]
https://github.com/inisis/brocolli/issues/8 可以参考下这个

**Comment by yw2278** [comment]
我咨询下，pytorch 0.4.1可以支持这个脚本么

**Comment by inisis** [comment]
转模型需要使用0.4.0的版本

**Comment by yw2278** [comment]
似乎这个问题是我模型detection类的问题，我这个模型有ssd结构，有个ssd转onnx的帖子也遇到了类似问题
https://github.com/onnx/onnx/issues/1020这里面是onnx不支持legacy function，但是这个脚本也没用到onnx就很奇怪

**Comment by inisis** [comment]
我的这个工具其实就是把 转 onnx 的步骤hack了一下，直接转成caffe了。本质上和pytorch->onnx->caffe是一样的。  但是为什么我要做一个这样的工具呢。因为很多时候pytorch->onnx会有些问题，我用我的工具可以比较快速和方便的debug。

**Comment by yw2278** [comment]
哦哦原来这样，那我试试看这个onnx的办法改写下detection类
