### ISSUE TITLE
PytorchParser报错

### ISSUE THREAD

**Issue by ycdhqzhiai** [inisis/brocolli#12]
@inis 你好，我在转换模型时候报output 2 of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.请问你有遇见过吗？
![image](https://user-images.githubusercontent.com/12273405/66731859-106e3180-ee8c-11e9-9819-6bb74aa1f679.png)

**Comment by inisis** [comment]
你好，

    可以考虑把网络结构图发给我看下吗。 发我邮箱就可以。

祝好

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。
