### ISSUE TITLE
pytorch版本以及upsample问题

### ISSUE THREAD

**Issue by xs-trinity-lwei** [inisis/brocolli#13]
您好，inisis，您的工程非常不错，我的问题如下：1、您工程里支持的版本是0.4.0，我的pytorch项目中包含upsample layer ，torch.onnx.export()貌似不支持upsample，但是我现在用的最新版1.3可以导出，您的建议是什么呢？2、我的工程结构类似于retinanet，不知道您的项目能否完美转换。很期待您的解惑，谢谢！

**Comment by inisis** [comment]
1. 如果是想用我的工具转caffe的话，pytorch0.4.0是必须的。
2. 正在尝试转换

**Comment by inisis** [comment]
https://github.com/inisis/brocolli/tree/desmond_retinanet 

此 issue 暂时关闭，有任何更新欢迎再次打开。
