### ISSUE TITLE
 errors in using pytorch_model_converter.py

### ISSUE THREAD

**Issue by luoduo21** [inisis/brocolli#14]
output = self.detect(
                loc.view(loc.size(0), -1, 4),                   # loc preds
                self.softmax(conf.view(conf.size(0), -1,
                             self.num_classes)),                # conf preds
                self.priors.type(type(x.data.type()))                  # default boxes
            )
 output 2 of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.

but when I Modify the code
output = (
                 loc.view(loc.size(0), -1, 4),  # loc preds
                 self.softmax(conf.view(-1, self.num_classes)),  # conf preds
             )
Traceback (most recent call last):
  File "/home/zt/brocolli-master/tests/pytorch_model_converter.py", line 55, in <module>
    pytorch_parser.run(model_file)
  File "/home/zt/brocolli-master/converter/core/parser.py", line 18, in run
    text_net, binary_weights = self.gen_IR()
  File "/home/zt/brocolli-master/converter/pytorch/pytorch_parser.py", line 126, in gen_IR
    layer_data = func(current_node)
  File "/home/zt/brocolli-master/converter/pytorch/pytorch_parser.py", line 228, in rename_Conv
    weight = self.state_dict[weights_name]
KeyError: 'base.weight'

Please help me.

**Comment by inisis** [comment]
Hi, you should uncomment line 156 in ssd.py to convert the model.

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。

**Comment by BigChaHu** [comment]
Hi, my issue is very similar to the question above,
weight = self.state_dict[weights_name] 
KeyError: '.weight',
I uncomment line 156 in ssd.py to convert the model and successd,but the model converted lost many layers

**Comment by inisis** [comment]
@BigChaHu the lost layers are meant for postprocess, you should use ssd_layers.py to add them
