### ISSUE TITLE
How to feed a tuple of inputs?

### ISSUE THREAD

**Issue by ycxia** [inisis/brocolli#17]
I want to convert siamrpn which has two inputs to caffe , how to do it? thank you

**Comment by inisis** [comment]
Can you paste a link for that model in pytorch. I will check it.

**Comment by ycxia** [comment]
@inisis https://github.com/STVIR/pysot  this is original repo.

https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md  this contains models

thank you

**Comment by hongjizhu** [comment]
@ycxia I have same problem with you. you already do well it ?

**Comment by inisis** [comment]
Hi, I tested your code, this model cannot be conveterd to caffe, because for the xcorr module, the conv2d is dynamic, this can be achieved it pytorch but not in caffe. However, brocolli now supports multi inputs.

> @inisis https://github.com/STVIR/pysot this is original repo.
> 
> https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md this contains models
> 
> thank you
