### ISSUE TITLE
运行pytorch_model_converter.py出错

### ISSUE THREAD

**Issue by runaway** [inisis/brocolli#19]
我编译安装了https://github.com/inisis/caffe.git过后，在brocolli/tests下运行 pytorch_model_converter.py出现No module named 'ssd'的错误，import caffe是成功的，请问应该怎么解决呀？

$ python3 pytorch_model_converter.py
Traceback (most recent call last):
  File "pytorch_model_converter.py", line 19, in <module>
    from ssd import *
ModuleNotFoundError: No module named 'ssd'
free(): invalid pointer
Aborted (core dumped)

**Comment by inisis** [comment]
please reference #6
