### ISSUE TITLE
how to test your code

### ISSUE THREAD

**Issue by ylc2580** [inisis/brocolli#2]
hi,
   i want to test your code and then convert my model.but i could not find your "test_pytorch.py" file. and may some errors:No module named model.classifier.could you tell me how to solve this problem? thanks

**Comment by inisis** [comment]
Hi,
    Sorry, it's my mistake. I update my readme, and, in order to convert your owm model, you need to import your own model.py and load your state_dict or you can find reference here https://pytorch.org/tutorials/beginner/saving_loading_models.html. 

Best,
Desmond

**Comment by inisis** [comment]
Hi,

  A ssd example is available, you can try it and modify my code to fit your own.

Best,
Desmond

**Comment by ylc2580** [comment]
谢谢-_-


 
---Original---
