### ISSUE TITLE
ssd转caffe报错:   keyerror: '.weight' 

### ISSUE THREAD

**Issue by 8125345** [inisis/brocolli#25]
调试的时候，运行到pytorch_parser.run(model_file)报错：
pytorch_parser.run(model_file)
text_net,binary_weight = self.genIR()
layer-data=fun(current_node)
weight = self.state_dict[weight_name]
keyerror: '.weight' 

您知道问题出在哪里吗？
我的环境是：torch0.4
                     numpy'1.14.3'(这个和要求的不一样)

**Comment by 8125345** [comment]
因为我之前不是用的老哥发的ssd300voc，然后换成ssd300voc之后，这个错误没了，但是还是运行到pytorch_parser.run(model_file)报错：attributrError: norm_param
这是什么原因呀
多谢

**Comment by inisis** [comment]
你好，请用这个 caffe https://github.com/inisis/caffe。

**Comment by 8125345** [comment]
> 你好，请用这个 caffe [https://github.com/inisis/caffe。](https://github.com/inisis/caffe%E3%80%82)
您好：
       我cmake您这个caffe 的时候报错：
    CMakeFiles/cmTC_6dcc5.dir/CheckSymbolExists.c.o：在函数‘main’中：
  CheckSymbolExists.c:(.text+0x16)：对‘pthread_create’未定义的引用
  /usr/bin/ld: 找不到 -lpthreads
  collect2: error: ld returned 1 exit status
 CMakeFiles/cmTC_773c8.dir/build.make:97: recipe for target 'cmTC_773c8' failed
  make[1]: *** [cmTC_773c8] Error 1
  make[1]: Leaving directory '/home/python/caffe-master/build/CMakeFiles/CMakeTmp'
  Makefile:126: recipe for target 'cmTC_773c8/fast' failed
 make: *** [cmTC_773c8/fast] Error 2


我看cmake文件里也有find thread.
cmake 时，说找不到thread-create。
我是在linux下安装的。因为需要链接anaconda的python,cmake可以看是否链接成功，所有没有直接make。

**Comment by 8125345** [comment]
> 你好，请用这个 caffe [https://github.com/inisis/caffe。](https://github.com/inisis/caffe%E3%80%82)

谢谢您，我换了caffe环境就好了，那些报错也解决了。多谢多谢
