### ISSUE TITLE
关于example.json的疑问

### ISSUE THREAD

**Issue by 8125345** [inisis/brocolli#26]
老哥，有个问题，其实在pytorch_model_converter里的pytorch_parser.run(model_file)之后，ssd的caffemodel和prototxt就已经生成了。
后面为什么要再跑ssd_layer.py example.json pytorch_model/best.pth.prototxt new.prototxt ，其中example.json文件是起什么作用呢。

多谢。

**Comment by 8125345** [comment]
是不是因为在pytorch_model_converter过程中把detection的部分去掉了，需要在ssd_layer.py里重新加上

**Comment by inisis** [comment]
对的

**Comment by 8125345** [comment]
> 对的

那example.json文件是起什么作用的呢

**Comment by inisis** [comment]
example.json 就是用来配置参数用的，因为后面的detection部分，没有可训练的参数，所以转模型的时候去掉了，转完之后再加上。

**Comment by 8125345** [comment]
> example.json 就是用来配置参数用的，因为后面的detection部分，没有可训练的参数，所以转模型的时候去掉了，转完之后再加上。
get it ,多谢您。这个问题可以关了。
