### ISSUE TITLE
你好，yolov5-6转换会报错list index out of range

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [inisis/brocolli#36]
pytorch_graph.py->extract()->line 130

因为不在同一台电脑，以上是出问题的定位，请见谅

**Comment by ZHEQIUSHUI** [comment]
我用onnx2caffe也会有类似的问题，好像是因为这里，t'ran'stranspose之后，同时作为输入和输出，导致找不到296节点

![c5a78f72cb1cbd85ca3425699fcbf66](https://user-images.githubusercontent.com/46700201/153785785-dccd2716-75be-4060-ae65-8a57efa8ff82.jpg)

**Comment by ZHEQIUSHUI** [comment]
![74591ab055905e16f57f9b5d1983d49](https://user-images.githubusercontent.com/46700201/153785852-292022f9-2e9c-471d-8286-6009dcf52022.jpg)

**Comment by inisis** [comment]
> 

可以提供下 模型 代码吗。

**Comment by inisis** [comment]
> pytorch_graph.py->extract()->line 130
> 
> 因为不在同一台电脑，以上是出问题的定位，请见谅

yolo的话 你可以试下这个 https://github.com/zhiqwang/yolov5-rt-stack ，一站式部署，不用自己转模型了。

**Comment by inisis** [comment]
> pytorch_graph.py->extract()->line 130
> 
> 因为不在同一台电脑，以上是出问题的定位，请见谅

你好，brocolli现在支持yolov5了，参见test/test_nets.py test_yolov5部分。

**Comment by ZHEQIUSHUI** [comment]
谢谢您
