### ISSUE TITLE
 RuntimeError: Exporting the operator max_unpool2d to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch 

### ISSUE THREAD

**Issue by hlcool** [inisis/brocolli#37]
RuntimeError: Exporting the operator max_unpool2d to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch

**Comment by inisis** [comment]
>  RuntimeError: Exporting the operator max_unpool2d to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch 

Hi, you need to add following line in torch.onnx.symbolic_opset13.py

''' 
def max_unpool2d(g, self, indices, output_size):
    return g.op("MaxUnpool", self, indices, output_size)
'''

**Comment by inisis** [comment]
hi，docker env is provided, you can run your code in docker.

**Comment by hlcool** [comment]
Great， 3Q
