### ISSUE TITLE
 Exporting the operator linalg_norm to ONNX opset version 13 is not supported

### ISSUE THREAD

**Issue by kv55** [inisis/brocolli#38]
RuntimeError: Exporting the operator linalg_norm to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by inisis** [comment]
Hi, you can use the docker image to convert your model, the env is complete, you can also join our qq group to get quick fix.

**Comment by kv55** [comment]
I tried with docker image and could  convert the model. 
Thank you so much.
