### ISSUE TITLE
KeyError: 'onnx:ScatterND' YOLOv5 conversion

### ISSUE THREAD

**Issue by kv55** [inisis/brocolli#39]
While trying to convert the YOLOv5 model, I'm getting KeyError for 'onnx:ScatterND', 'onnx:Range', 'onnx:Expand', 'onnx:Where'  and 'onnx:Equal'. Could you please help me on how to get rid this error? I have got the same error when tried with the docker image also.

**Comment by inisis** [comment]
> While trying to convert the YOLOv5 model, I'm getting KeyError for 'onnx:ScatterND', 'onnx:Range', 'onnx:Expand', 'onnx:Where'  and 'onnx:Equal'. Could you please help me on how to get rid this error? I have got the same error when tried with the docker image also.

Hi，you can use the latest docker image

**Comment by kv55** [comment]
It worked when I tried with the latest docker image. Thank you so much.
