### ISSUE TITLE
KeyError: 'prim::PythonOp' while converting SSD300 with phase = "test"

### ISSUE THREAD

**Issue by kv55** [inisis/brocolli#42]
While I was trying to convert SSD300_vgg16 model to Caffe with phase = 'test' instead of 'export' I got the following error :
File "/root/brocolli/converter/pytorch/pytorch_caffe_parser.py", line 138, in gen_IR
    node_type = layer_map[onnx_node_type]
KeyError: 'prim::PythonOp'

**Comment by inisis** [comment]
> While I was trying to convert SSD300_vgg16 model to Caffe with phase = 'test' instead of 'export' I got the following error :
> 
> File "/root/brocolli/converter/pytorch/pytorch_caffe_parser.py", line 138, in gen_IR
> 
>     node_type = layer_map[onnx_node_type]
> 
> KeyError: 'prim::PythonOp'
> 
> 

can you provide your model. I have a ssd model under custom_models which can be coverted to caffe, you can follow it.

**Comment by kv55** [comment]
I have used the ssd.py file in custom_models folder, but with some modifications. I have added detect and nms functions and also, some changes to handle version differences. In the test_caffe_nets.py file used build_ssd('test') instead of build_ssd('export').
[ssd.zip](https://github.com/inisis/brocolli/files/8241747/ssd.zip)

**Comment by inisis** [comment]
> I have used the ssd.py file in custom_models folder, but with some modifications. I have added detect and nms functions and also, some changes to handle version differences. In the test_caffe_nets.py file used build_ssd('test') instead of build_ssd('export'). [ssd.zip](https://github.com/inisis/brocolli/files/8241747/ssd.zip)

Hi, right now you can only convert the backbone to caffe, if you want to convert priorbox and detection_out part, you should first convert model created by build_ssd('export'), then, you should fill this json by using your own parameter, https://github.com/inisis/brocolli/blob/2a15ac07010114716aef7fbb9be1f6d6b35e21a5/tests/example.json and use this https://github.com/inisis/brocolli/blob/2a15ac07010114716aef7fbb9be1f6d6b35e21a5/tests/ssd_layer.py to add  priorbox and detection_out layer to your previously converted ssd backbone.

**Comment by kv55** [comment]
> > I have used the ssd.py file in custom_models folder, but with some modifications. I have added detect and nms functions and also, some changes to handle version differences. In the test_caffe_nets.py file used build_ssd('test') instead of build_ssd('export'). [ssd.zip](https://github.com/inisis/brocolli/files/8241747/ssd.zip)
> 
> Hi, right now you can only convert the backbone to caffe, if you want to convert priorbox and detection_out part, you should first convert model created by build_ssd('export'), then, you should fill this json by using your own parameter, https://github.com/inisis/brocolli/blob/2a15ac07010114716aef7fbb9be1f6d6b35e21a5/tests/example.json and use this https://github.com/inisis/brocolli/blob/2a15ac07010114716aef7fbb9be1f6d6b35e21a5/tests/ssd_layer.py to add priorbox and detection_out layer to your previously converted ssd backbone.
Thank you for the suggestion
I could convert SSD by following the steps mentioned above. But during inference with the converted model. I got the following error:
reshape_layer.cpp:80] Check failed: 0 == bottom[0]->count() % explicit_count (0 vs. 5) bottom count (34928) must be divisible by the product of the specified dimensions (21)
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by inisis** [comment]
> > > I have used the ssd.py file in custom_models folder, but with some modifications. I have added detect and nms functions and also, some changes to handle version differences. In the test_caffe_nets.py file used build_ssd('test') instead of build_ssd('export'). [ssd.zip](https://github.com/inisis/brocolli/files/8241747/ssd.zip)
> > 
> > 
> > Hi, right now you can only convert the backbone to caffe, if you want to convert priorbox and detection_out part, you should first convert model created by build_ssd('export'), then, you should fill this json by using your own parameter, https://github.com/inisis/brocolli/blob/2a15ac07010114716aef7fbb9be1f6d6b35e21a5/tests/example.json and use this https://github.com/inisis/brocolli/blob/2a15ac07010114716aef7fbb9be1f6d6b35e21a5/tests/ssd_layer.py to add priorbox and detection_out layer to your previously converted ssd backbone.
> 
> Thank you so much for the suggestions. I could convert SSD in inference mode by following the above mentioned steps.

Good for you
