### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'img_metas'

### ISSUE THREAD

**Issue by kv55** [inisis/brocolli#44]
While trying to convert MMDetection SSD300 model the following error occurred:
TypeError: forward() missing 1 required positional argument: 'img_metas'

**Comment by inisis** [comment]
Hi, have you tried the latest torch fx based code to convert your model, if so, you might have not pass img_metas as input, for example, the original model needs two input, but you only give one.

**Comment by kv55** [comment]
It worked .
Thank you very much
