### ISSUE TITLE
TypeError: torch.Size() takes an iterable of 'int' (item 0 is 'Tensor')

### ISSUE THREAD

**Issue by Haleski47** [inisis/brocolli#47]
Hi, when i run the demo

from brocolli.converter.pytorch_onnx_parser import PytorchOnnxParser
model = models.resnet18(pretrained=False)
x = torch.rand(1 ,3 ,224, 224)
runner = PytorchOnnxParser(model, x)
runner.convert()
runner.save("resnet18.onnx")
runner.check_result()

it tell me: 
---> 36         self.input_shape = map_replace(input_shape, get_torch_size)

/opt/conda/lib/python3.7/site-packages/brocolli/converter/utils.py in map_replace(args, fn)
     44         return list(map_replace(elem, fn) for elem in args)
     45     else:
---> 46         return fn(args)

/opt/conda/lib/python3.7/site-packages/brocolli/converter/utils.py in get_torch_size(obj)
     25 
     26 def get_torch_size(obj):
---> 27     return torch.Size(obj)

TypeError: torch.Size() takes an iterable of 'int' (item 0 is 'Tensor')

i wonder what cause the problem

**Comment by inisis** [comment]
Hi, I cannot reproduce your result, it work fine for me with pytorch version 1.9.0, can you provide your venv version info?

**Comment by inisis** [comment]
Can you download our source code to run the demo, instead of using the package from pip source.
