### ISSUE TITLE
pip install brocolli-caffe &源码安装报错。

### ISSUE THREAD

**Issue by w-jinkui** [inisis/brocolli#49]
python环境为3.7.5 
建立venv虚拟环境后，在虚拟环境中安装
pip install brocolli
pip install brocolli-caffe
报错：
![2023-02-13 22-30-47屏幕截图](https://user-images.githubusercontent.com/22999222/218485852-391bf95e-4167-4698-9c7e-9b3d1ac8c80d.png)

**Comment by inisis** [comment]
你好，朋友，加个QQ群，597059928。你这个日志信息太不明显了，没有截取到关键信息。

**Comment by inisis** [comment]
你应该是没有安装conda，用的是venv。brocolli-caffe必须要conda环境，因为需要安装一些依赖。
