### ISSUE TITLE
pytorch 1.0.1

### ISSUE THREAD

**Issue by suntaiwu** [inisis/brocolli#5]
大佬，后续会支持pytorch 1.0版本么

**Comment by inisis** [comment]
你好。 1.0 的 模型可以在 0.4.0 版本下面转。 你需要有两个版本的 pytorch 环境。 一个用来训练模型，一个用来转模型。

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。
