### ISSUE TITLE
How to use the quantizers with CUDA？

### ISSUE THREAD

**Issue by athony-neo** [inisis/brocolli#52]
Hi ，Thank you for your wonderful and impressive project！ seen the test/quantization/test_quanzation_nets.py  use the cpu to load nets and datasets, I'd like follow your idea to trace my model and quantizate with GPU ways,but when i set model.cuda() and use the input_data.cuda() then the error raised:RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
then go to the erro raised location: dummy_input = self.gen_input_tensor(self.input_shape) 
    def gen_input_tensor(self, shapes):
        input_tensor = []
        for shape in shapes:
            if isinstance(shape, (tuple, list)):
                if all(isinstance(element, int) for element in shape):
                    input_tensor.append(torch.rand(shape).to(torch.float32))
                else:
                    input_tensor.append(self.gen_input_tensor(shape))
            else:
                input_tensor.append(torch.rand(shape).to(torch.float32))

        return input_tensor
is this func determine the inputs's type from my origin "input_data.cuda()" to other kind types that finally caused the error?
and would pls tell some details about how to use your demo with our own datasets and nets in a GPU way？
thank you very much！

**Comment by athony-neo** [comment]
the more details is the error is rasied after pytorch_quantizer = PytorchQuantizer(model,shape) , it means the graphmodule instance has be generated , but then pytorch_quantizer.fuse() rasied the weights's tensor tpye doesn't match the data's tensor type

**Comment by inisis** [comment]
Hi, GPU support will be added soon.

**Comment by inisis** [comment]
gpu support is added, see [aea703f](https://github.com/inisis/brocolli/commit/aea703f7f4d04b3994bb8b91ff5c7beffcebd29e)
