### ISSUE TITLE
  AttributeError: 'PytorchQuantizer' object has no attribute 'prepare'? how to solve

### ISSUE THREAD

**Issue by scuizhibin** [inisis/brocolli#59]

**Comment by inisis** [comment]
Hi, you can change pytorch_quantizer.prepare() to pytorch_quantizer.prepare_calibration()

**Comment by scuizhibin** [comment]
qat&nbsp;也需要校准数据集吗？


---Original---
From: ***@***.***&gt;
Date: Mon, Jul 31, 2023 10:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [inisis/brocolli]   AttributeError: 'PytorchQuantizer' object hasno attribute 'prepare'? how to solve (Issue #59)




 
Hi, you can change pytorch_quantizer.prepare() to pytorch_quantizer.prepare_calibration()
 
&mdash;

**Comment by inisis** [comment]
Hi, you can checkout to d70f7b01d7ff86b4fcbfa833f1f64a0e24ca5e09, you it will be all fine.

**Comment by inisis** [comment]
close as not active.
