### ISSUE TITLE
ImportError: No module named 'ssd'

### ISSUE THREAD

**Issue by Jianglongyu** [inisis/brocolli#6]
Hi, I'm newer to use caffe, so when I run this project  some problem comes out.  There is no ssd directory or package in project, so whether it's code by author or need to install ?  confusions

**Comment by inisis** [comment]
Hi,
ssd.py should be downloaded from the link in readme.

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。
