### ISSUE TITLE
NotImplementedError: module InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False) is not implemented

### ISSUE THREAD

**Issue by ouxiand** [inisis/brocolli#63]
Thank you for sharing such an excellent open source component！

I encountered a problem:
  File "/pycode/brocolli/brocolli/converter/pytorch_caffe_parser.py", line 51, in convert
    self.text_net, self.binary_weights = self.gen_ir()
  File "/pycode/brocolli/brocolli/converter/pytorch_caffe_parser.py", line 230, in gen_ir
    raise NotImplementedError("module %s is not implemented" % (module))
NotImplementedError: module InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False) is not implemented

May I ask how to handle it?

**Comment by inisis** [comment]
Hi, friend, caffe doesn't support InstanceNorm, maybe you should change InstanceNorm to BatchNorm for deployment
