### ISSUE TITLE
need support for efficient way to write act_scale,wt_scale,output_scale to txt

### ISSUE THREAD

**Issue by ECEDong** [inisis/brocolli#64]

**Comment by inisis** [comment]
https://github.com/inisis/brocolli/commit/3e4803e7c114b39b5662413b383fd7c5e67243ff support that, see https://github.com/inisis/brocolli/commit/3e4803e7c114b39b5662413b383fd7c5e67243ff#diff-5ed31920edb430d73adff69f9ff854db9cd80aa9f4a5a82bd4a987d11c1275c5
