### ISSUE TITLE
老哥，怎么把ssd从pytorch转caffe。。。

### ISSUE THREAD

**Issue by ZhongyuanW** [inisis/brocolli#8]
如题。。。

**Comment by inisis** [comment]
1. 按照readme 先从 ssd repo 里面 把ssd.py 拷贝到 转模型的时候repo 里面。
2. 转模型的时候 把 ssd.py 的 156行解注释 然后跑。
3. 转成功之后，再跑ssd_layer.py
这时模型就转好了。

**Comment by ZhongyuanW** [comment]
谢谢！我能转了，但是我ssd的backbone是用的一个mobilenet类，错误信息是找不到mobilenet.bottleneck0.conv1.weights。
然后我又仿照vgg的方式把mobilenet结构用list直接写进去，就不会报错了，但是这种就不能读取预训练模型进行训练了，请问有什么解决的办法吗。。。

**Comment by inisis** [comment]
我的建议，你可以把你的原来模型的model.state_dict.keys()打印出来，这个名字里面应该只有bottleneck0.conv1.weights。你可以想个办法把mobilenet加到key里面去。

**Comment by ZhongyuanW** [comment]
谢谢大佬！

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。
