### ISSUE TITLE
您好想问下其他的pytorch模型怎么转换成caffe？

### ISSUE THREAD

**Issue by yw2278** [inisis/brocolli#9]

**Comment by inisis** [comment]
你好，你需要把你的模型描述文件放到这个repo里面来。具体可以看下 pytorch_model_converter.py 第 51 行。 穿进去的 model_file 是你自定义的就可以

**Comment by yw2278** [comment]
好的谢谢您，我试一下

**Comment by inisis** [comment]
此 issue 暂时关闭，有任何更新欢迎再次打开。
